version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 33DLtmGBKcAdjZze
      MYSQL_DATABASE: tech-challenge
      MYSQL_USER: admin
      MYSQL_PASSWORD: 5qtX6EUZLFhdzni6
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: api
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tech-challenge
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: 5qtX6EUZLFhdzni6
#
#volumes:
#  mysql_data:
